---

---

# Ashlyn R Effective Teamwork {-}

Teamwork - It makes the dream work!

The article I read was called the *Nine Characteristics of great teamwork* by Steve Hogarty.

[Click here to vist the article!](https://www.wework.com/ideas/professional-development/management-leadership/nine-characteristics-of-great-teamwork)

This was an article that focused on teamwork in a more corporate or work setting.
However, I think that these ideas are still applicable in our setting.
Teamwork is defined as how people interact with each other, and how individual skills and attributes are combined in an effective way.
One key noted is that other things can impact teamwork took: outlook, attitudes, and the structure of the space.
The purpose of a team and teamwork is to achieve a shared goal.
Another thing that the article noted is that teamwork looks different in different settings but communication is key.

My biggest takeaways from the article were to have clear, concise, and effective communication.
Setting goals, timelines, and the end product very clearly defined.
Utilizing these pieces me and my partner can achieve our end result.
